


;functions
externdef _malloc:proc
externdef _calloc:proc
externdef _free:proc
externdef _realloc:proc
externdef __exit:proc
externdef _exit:proc
externdef __onexit:proc
externdef _doexit:proc
externdef __amsg_exit:proc
externdef __initterm:proc
externdef __heap_init:proc
externdef __getptd:proc
externdef __errno:proc
externdef ___doserrno:proc
externdef __mtinit:proc
externdef __initptd:proc
externdef __freeptd:proc
externdef _siglookup:proc
externdef __msize:proc
externdef __expand:proc
externdef ___onexitinit:proc
externdef _memcpy:proc
externdef _memset:proc
externdef _memcmp:proc
externdef _strcmp:proc
externdef _atexit:proc
externdef __ftol:proc
externdef _abs:proc
externdef _sqrt:proc
externdef _tan:proc
externdef _sprintf:proc
externdef _strcpy:proc
externdef _strchr:proc
externdef _strstr:proc
externdef _atoi:proc
externdef _isprint:proc
externdef __alloca_probe:proc
externdef _rand:proc
externdef _strtoul:proc
externdef _strtol:proc
externdef _strlen:proc
externdef _strcat:proc
externdef _strncat:proc
externdef _strrchr:proc
externdef __strdup:proc
externdef __strcmpi:proc
externdef __strnicmp:proc
externdef __itoa:proc
externdef _qsort:proc
externdef _fopen:proc
externdef _fseek:proc
externdef _fgets:proc
externdef _fputs:proc
externdef _fclose:proc
externdef _fprintf:proc
externdef _ftell:proc
externdef _fflush:proc
externdef _fread:proc
externdef _fwrite:proc
externdef __fdopen:proc
externdef __read:proc
externdef __write:proc
externdef __lseek:proc
externdef __sopen:proc
externdef __close:proc
externdef _sin:proc
externdef _cos:proc
externdef _acos:proc
externdef _atan:proc
externdef _pow:proc
externdef _exp:proc
externdef _atan2:proc
externdef _log10:proc
externdef _log:proc
externdef _isalnum:proc
externdef _isalpha:proc
externdef _isupper:proc
externdef _islower:proc
externdef _isspace:proc
externdef _isdigit:proc
externdef _sscanf:proc
externdef _tolower:proc
externdef _memchr:proc
externdef __hypot:proc
externdef _fabs:proc
externdef _atol:proc
externdef _atof:proc
externdef _bsearch:proc
externdef __beginthread:proc
externdef __endthread:proc
externdef __beginthreadex:proc
externdef __endthreadex:proc
externdef __spawnlp:proc
externdef __unlink:proc
externdef __alldiv:proc
externdef _srand:proc
externdef _abort:proc
externdef __except_handler3:proc
externdef _printf:proc
externdef _toupper:proc
externdef __allmul:proc
externdef _time:proc
externdef _gmtime:proc
externdef _localtime:proc
externdef _mktime:proc
externdef _strftime:proc
externdef __EH_prolog:proc
externdef ___CxxFrameHandler:proc
externdef __CxxThrowException@8:proc
externdef ??_L@YGXPAXIHP6EX0@Z1@Z:proc
externdef ??_M@YGXPAXIHP6EX0@Z@Z:proc
externdef _clearerr:proc
externdef __fullpath:proc
externdef __mbsrchr:proc
externdef __mbsstr:proc
externdef __mbsspn:proc
externdef __mbscspn:proc
externdef __mbsinc:proc
externdef __setmode:proc
externdef __setmbcp:proc
externdef __mbscmp:proc
externdef __mbschr:proc
externdef __mbsupr:proc
externdef __mbslwr:proc
externdef __mbspbrk:proc
externdef __mbsrev:proc
externdef __mbclen:proc
externdef _wcslen:proc
externdef __purecall:proc
externdef __splitpath:proc
externdef __ismbcdigit:proc
externdef __ismbcspace:proc
externdef _vsprintf:proc
externdef __get_osfhandle:proc
externdef __open_osfhandle:proc
externdef _strncpy:proc
externdef start:proc



;data
externdef ??_7type_info@@6B@:dword
externdef ??_R0?AVtype_info@@@8:dword

externdef _a2_stdout:dword
externdef _a2_stderr:dword
externdef _a2_mbctype:byte
externdef _a2_argc:dword
externdef _a2_argv:dword
externdef _a2_pioinfo:dword



;In main.asm


externdef sub_5F4A3F:proc
externdef sub_5F4CFA:proc
externdef sub_5F54CC:proc
externdef sub_5F642B:proc
externdef sub_5F6451:proc
externdef sub_5D9D9B:proc
externdef unknown_libname_409:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_453:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_499:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_526:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_540:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_541:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_542:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_543:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_544:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_545:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_546:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_547:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_548:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_549:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_550:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_551:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_552:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_553:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_554:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_555:proc ; MFC 3.1-14.0 32bit

externdef unknown_libname_557:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_558:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_559:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_560:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_561:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_562:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_563:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_564:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_565:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_566:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_567:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_568:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_571:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_572:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_573:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_574:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_575:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_576:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_577:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_590:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_591:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_652:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_653:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_654:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_655:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_656:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_670:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_682:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_683:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_684:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_685:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_686:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_690:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_691:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_692:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_693:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_694:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_695:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_696:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_697:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_698:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_699:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_700:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_701:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_702:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_703:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_704:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_705:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_706:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_707:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_708:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_709:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_710:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_711:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_712:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_713:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_714:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_715:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_716:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_717:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_718:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_719:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_720:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_730:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_734:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_735:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_736:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_738:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_741:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_742:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_743:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_744:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_746:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_747:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_748:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_749:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_750:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_751:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_752:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_753:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_754:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_755:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_756:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_762:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_763:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_764:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_765:proc ; MFC 3.1-14.0 32bit
externdef unknown_libname_766:proc ; MFC 3.1-14.0 32bit
externdef sub_5F4548:proc
externdef sub_5F4685:proc
externdef sub_5F46F3:proc
externdef sub_5EFCB8:proc
externdef sub_5F4741:proc
externdef sub_5F4779:proc
externdef sub_5F47B1:proc
externdef sub_5F47E9:proc
externdef sub_5F48E9:proc
externdef sub_5F4953:proc
externdef sub_5E06F0:proc
externdef sub_5E0706:proc
externdef sub_5E0744:proc
externdef sub_5E0782:proc
externdef sub_5E07C0:proc
externdef j_unknown_libname_941:proc
externdef j_unknown_libname_942:proc
externdef sub_5F5AB8:proc
externdef sub_5F6477:proc
externdef sub_5F2BD3:proc

externdef _a2WinMain@16:proc




beginSection    MACRO   SectName
_crt$&SectName  SEGMENT DWORD alias(".CRT$&SectName") PUBLIC 'DATA'
                ENDM

endSection      MACRO   SectName
_crt$&SectName  ENDS
                ENDM